# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.DecimalField(decimal_places=1, default=None, max_digits=2)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=None, max_digits=2)),
                ('floors', models.IntegerField(default=1)),
                ('paint_color', models.TextField(default=None)),
                ('style', models.TextField(choices=[('beach', 'Beach'), ('bungalow', 'Bungalow'), ('colonial', 'Colonial'), ('contemporary', 'Contemporary'), ('contemporary-craftsman', 'Contemporary Craftsman'), ('country', 'Country'), ('english-cottage', 'English Cottage'), ('modern', 'Modern')], default='contemporary')),
                ('garage', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3)),
                ('address_1', models.CharField(default=None, max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(default='Mishawaka', max_length=64)),
                ('state', models.CharField(default='IN', max_length=2)),
                ('zip_code', models.CharField(default='46544', max_length=5)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'db_table': 'house',
            },
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set([('address_1', 'address_2', 'city', 'state', 'zip_code')]),
        ),
    ]
