# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='style',
            field=models.CharField(choices=[('beach', 'Beach'), ('bungalow', 'Bungalow'), ('colonial', 'Colonial'), ('contemporary', 'Contemporary'), ('contemporary-craftsman', 'Contemporary Craftsman'), ('country', 'Country'), ('english-cottage', 'English Cottage'), ('modern', 'Modern')], default='contemporary', max_length=128),
        ),
    ]
