# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('make', models.TextField(default=None)),
                ('model', models.TextField(default=None)),
                ('year', models.IntegerField(default=None)),
                ('color', models.TextField(default=None)),
                ('vehicle_type', models.TextField(default=None)),
                ('serial_number', models.IntegerField(default=None, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
            },
        ),
    ]
