# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('make', 'model', 'year', 'color', 'vehicle_type', 'serial_number')]),
        ),
    ]
