# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.TextField(default=None, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be in format ###-##-####', regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('f_name', models.TextField(default=None)),
                ('m_intital', models.CharField(default=None, max_length=1)),
                ('l_name', models.TextField(default=None)),
                ('date_of_birth', models.DateField(default=None)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.House')),
                ('vehicles', models.ManyToManyField(to='vehicle.Vehicle')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'person',
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('f_name', 'm_intital', 'l_name', 'date_of_birth', 'SSN')]),
        ),
    ]
